//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExam.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LAB_AEntities1 : DbContext
    {
        public LAB_AEntities1()
            : base("name=LAB_AEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Itineray> Itinerays { get; set; }
        public virtual DbSet<PackingItem> PackingItems { get; set; }
        public virtual DbSet<Share> Shares { get; set; }
        public virtual DbSet<TripPlan> TripPlans { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
