//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingItem
    {
        public int ItemId { get; set; }
        public int TId { get; set; }
        public string ItemName { get; set; }
        public int Quantity { get; set; }
        public string Packed { get; set; }
    
        public virtual TripPlan TripPlan { get; set; }
    }
}
