//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TripPlan()
        {
            this.Itinerays = new HashSet<Itineray>();
            this.PackingItems = new HashSet<PackingItem>();
            this.Shares = new HashSet<Share>();
        }
    
        public int TripId { get; set; }
        public int UserID { get; set; }
        public string Tittle { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Budget { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itineray> Itinerays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackingItem> PackingItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Share> Shares { get; set; }
        public virtual User User { get; set; }
    }
}
